version: '3.8'
services:
  backend:
    build: ./backend
    container_name: expressapi_cont
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    container_name: reactapp_cont
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
